import { useState } from 'react';
import { X, ArrowRight, ArrowLeft } from 'lucide-react';

const STEPS = [
  {
    title:       'Community Risk Index',
    description: 'The composite score (0–100) aggregates five sector readings into a single community health index. A score below 50 triggers automated intervention protocols. Switch communities using the selector in the navigation bar.',
    anchor:      'hero',
    position:    'bottom',
  },
  {
    title:       'Five-Sector Monitoring',
    description: 'PrimeLink monitors Environment, Agriculture, Health, Finance, and IoT simultaneously. Scores update every three seconds from 127 field sensors. Cross-sector correlation is computed continuously — a declining environment score will propagate to agriculture and health within minutes.',
    anchor:      'gauges',
    position:    'bottom',
  },
  {
    title:       'Risk Score Timeline',
    description: 'The 24-hour chart tracks composite and per-sector trends. Sustained downward movement across multiple sectors indicates a developing multi-sector crisis and pre-arms the parametric finance engine.',
    anchor:      'chart',
    position:    'bottom',
  },
  {
    title:       'Alert Feed',
    description: 'Real-time alerts are generated by the risk engine when sector scores cross defined thresholds or show rapid directional change. Alerts are classified as informational, elevated, or critical and distributed to relevant government agencies automatically.',
    anchor:      'alerts',
    position:    'top',
  },
  {
    title:       'Parametric Finance Engine',
    description: 'When the finance score drops below the parametric trigger threshold, insurance payouts are disbursed automatically to enrolled households — no claims adjusters, no delays. The trigger meter is visible at the base of this panel.',
    anchor:      'finance',
    position:    'top',
  },
  {
    title:       'Crisis Simulation',
    description: 'Use the scenario control in the bottom-right corner to run a live demonstration: Drought, Flood, or Disease Outbreak. Each simulation plays out in real time over 28 seconds, showing detection, cross-sector propagation, automated response, and recovery.',
    anchor:      'scenario',
    position:    'top',
  },
];

// Highlight ring positions keyed by anchor — approximate viewport-relative coordinates
// These are used to draw an attention ring on the appropriate section of the page
const ANCHOR_STYLES = {
  hero:     { top: '88px',  left: '0',    right: '0',  height: '96px'  },
  gauges:   { top: '196px', left: '0',    right: '0',  height: '120px' },
  chart:    { top: '332px', left: '0',    right: '0',  height: '172px' },
  alerts:   { bottom: '420px', left: '0',    width: '50%', height: '298px' },
  finance:  { bottom: '420px', right: '0',   width: '50%', height: '298px' },
  scenario: { bottom: '60px',  right: '16px',width: '220px', height: '40px' },
};

export default function OnboardingTour({ onComplete }) {
  const [step,     setStep]     = useState(0);
  const [leaving,  setLeaving]  = useState(false);

  const current = STEPS[step];
  const isLast  = step === STEPS.length - 1;
  const isFirst = step === 0;

  const advance = () => {
    if (isLast) {
      finish();
    } else {
      setStep(s => s + 1);
    }
  };

  const retreat = () => { if (!isFirst) setStep(s => s - 1); };

  const finish = () => {
    setLeaving(true);
    setTimeout(onComplete, 400);
  };

  const anchorStyle = ANCHOR_STYLES[current.anchor] ?? {};

  return (
    <>
      {/* Dimmed overlay */}
      <div
        className="fixed inset-0 z-40 pointer-events-none"
        style={{ background: 'rgba(4,12,24,0.72)', transition: 'opacity 0.3s ease', opacity: leaving ? 0 : 1 }}
      />

      {/* Highlight ring */}
      <div
        key={current.anchor}
        className="fixed z-41 pointer-events-none rounded-lg animate-fade-in"
        style={{
          ...anchorStyle,
          border:     '1.5px solid rgba(0,200,150,0.5)',
          boxShadow:  '0 0 0 4px rgba(0,200,150,0.06), 0 0 24px rgba(0,200,150,0.12)',
          transition: 'all 0.35s ease',
        }}
      />

      {/* Tour card */}
      <div
        className="fixed z-50 bottom-16 left-1/2 -translate-x-1/2 w-full max-w-sm sm:max-w-md px-4 animate-slide-up"
        style={{ opacity: leaving ? 0 : 1, transition: 'opacity 0.35s ease' }}
      >
        <div
          className="rounded-xl p-5 shadow-2xl shadow-black/60"
          style={{ background: '#0B1628', border: '1px solid #1A2E4A' }}
        >
          {/* Step counter + dismiss */}
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-1.5">
              {STEPS.map((_, i) => (
                <button
                  key={i}
                  onClick={() => setStep(i)}
                  className="rounded-full transition-all"
                  style={{
                    width:      i === step ? '20px' : '6px',
                    height:     '6px',
                    background: i === step ? '#00C896' : '#1A2E4A',
                  }}
                />
              ))}
            </div>
            <button
              onClick={finish}
              className="p-1 rounded hover:bg-[#1A2E4A] transition-colors"
            >
              <X size={14} className="text-[#475569]" />
            </button>
          </div>

          {/* Content */}
          <p className="text-[10px] text-[#00C896] font-semibold uppercase tracking-widest mb-1">
            Step {step + 1} of {STEPS.length}
          </p>
          <h3 className="text-sm font-bold text-white mb-2">{current.title}</h3>
          <p className="text-xs text-[#94A3B8] leading-relaxed">{current.description}</p>

          {/* Navigation */}
          <div className="flex items-center justify-between mt-5">
            <button
              onClick={retreat}
              disabled={isFirst}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium text-[#64748B] border border-[#1A2E4A] hover:border-[#334155] hover:text-white transition-colors disabled:opacity-20 disabled:pointer-events-none"
            >
              <ArrowLeft size={11} strokeWidth={2.5} />
              Previous
            </button>

            <button
              onClick={advance}
              className="flex items-center gap-1.5 px-4 py-1.5 rounded-lg text-xs font-semibold text-white transition-opacity hover:opacity-85"
              style={{ background: '#00C896' }}
            >
              {isLast ? 'Get Started' : 'Next'}
              {!isLast && <ArrowRight size={11} strokeWidth={2.5} />}
            </button>
          </div>
        </div>
      </div>
    </>
  );
}
